### ISSUE TITLE
Abort streamed request

### ISSUE THREAD

**Issue by LostKobrakai** [sneako/finch#112]
Say I'm using Finch to proxy some request to an upstream http server I might want to stop the stream if the caller closed the connection:

```
Finch.stream(request, Pour.HTTP, conn, fn
  {:status, status}, conn -> 
    send_chunked(conn, status)
    
  {:headers, _}, conn -> 
    conn
    
  {:data, _}, conn -> 
    case Plug.Conn.chunk(conn, chunk) do
      {:ok, conn} -> conn
      {:error, :closed} -> # how to abort here
    end
end)
```

**Comment by thbar** [comment]
This can also be useful when e.g. you'd want to halt the processing based on headers or status. For instance, if one wants to use streaming to compute a checksum of the data, but only compute it if the status is 200, and ignore otherwise (or follow a redirect header etc).

**Comment by ericmj** [comment]
You cannot abort HTTP/1 requests, the only thing you can do is close the connection. If you want to make a choice based on the headers you should use `Expect: 100-continue`.

With HTTP/2 you can abort requests, Mint exposes that through `Mint.HTTP2.cancel_request/2`.

**Comment by thbar** [comment]
Thanks! To simulate the abortion, is there a recommended way to close an HTTP/1 connection inside a `Finch.stream` stream function?

**Comment by chargreezy** [comment]
To expand on this, when streaming in finch we pass a reducing function for status, headers and data. This underlying mint connection is not available inside these calls, would adding the mint connection to the call make the functionality possible.

Before:
```
      {:status, value}, {_, headers, body} ->
        {value, headers, body}
      {:headers, value}, {status, headers, body} ->
        {status, headers ++ value, body}
      {:data, value}, {status, headers, body} ->
        {status, headers, [value | body]}
```
After:
```
      {:status, value, mint}, {_, headers, body} ->
        {value, headers, body}
      {:headers, value, mint}, {status, headers, body} ->
        {status, headers ++ value, body}
      {:data, value, mint}, {status, headers, body} ->
        // Maybe close the connection with Mint.HTTP.close(mint)
```

**Comment by ericmj** [comment]
If you throw inside the streaming function the connection will be closed (for HTTP/1.1) and the request will be cancelled: https://github.com/sneako/finch/blob/main/test/finch/http1/integration_test.exs#L83

**Comment by sneako** [comment]
Thanks @ericmj, that is a great point! If you throw in your stream function HTTP/1 will close the connection [here](https://github.com/sneako/finch/blob/main/lib/finch/http1/conn.ex#L140) and HTTP/2 will cancel the request [here](https://github.com/sneako/finch/blob/main/lib/finch/http2/pool.ex#L75). I think that should be sufficient but if anyone can describe a situation where it would not be please share.

**Comment by chargreezy** [comment]
Thanks for the response! I saw the integration test but it's great to get a confirmation this is expected.
