### ISSUE TITLE
Support custom Mint transports

### ISSUE THREAD

**Issue by dannote** [sneako/finch#141]
Hi!

Mint natively (and silently) [supports](https://github.com/elixir-mint/mint/blob/dc655a2ebdf4c7a8556da4a0fb082b9549b54f2a/lib/mint/core/util.ex#L106) custom transports by accepting a module implementing `Mint.Core.Transport` behaviour:

```elixir
Mint.HTTP.connect(My.Custom.Module, "example.com", 80)
```

Although it's an undocumented (yet) feature, it works seamlessly. It would be great if Finch pools also accepted a tuple in the form of `{module, host, port}`. I saw the ongoing conversation about the UNIX socket (#139); this might be related.

**Comment by keathley** [comment]
@dannote Agreed, I think we should be able to solve both of these cases with the same solution.

**Comment by sneako** [comment]
Custom transports are not officially supported by Mint so I am not sure that we should try to add this feature that depends on a private API, see: https://github.com/elixir-mint/mint/pull/323

**Comment by keathley** [comment]
Oh good call @sneako. I hadn't realized that was private. Agreed that we shouldn't support a feature that is based on Mint's private API.
