### ISSUE TITLE
`Mint.UnsafeProxy` connection not handled in `Finch.Conn.request/6`

### ISSUE THREAD

**Issue by iwinux** [sneako/finch#157]
Hi, I'd like to report an issue of using Finch with HTTP proxy.

## Problem

Requests to plain HTTP (i.e.: non-HTTPS) URLs via proxy are handled in `Mint.UnsafeProxy`, but currently `Finch.Conn.request/6` is not aware of such case, resulting in `FunctionClauseError`.

## Reproduce

```elixir
defmodule FinchProxyTest.App do
  use Application

  def start(_type, _args) do
    children = [
      {Finch, name: FinchProxyTest, pools: pool_options()}
    ]

    Supervisor.start_link(children, strategy: :one_for_one)
  end

  def pool_options do
    %{host: host, port: port} = System.get_env("http_proxy", "") |> URI.parse()
    %{default: [protocol: :http1, conn_opts: [proxy: {:http, host, port, []}]]}
  end
end

# suppose env `http_proxy` is set
FinchProxyTest.Client.request "http://localhost:8000"
```

## Possible Solutions

* Handle `UnsafeProxy` connections in `Finch.HTTP1.Pool.request/5`

* Dynamic Pool Configs: allow users to pass in a callback instead of static pool configs (`fn (scheme, host, port) -> pool_config end`, for example)

**Comment by Hajto** [comment]
@bsedat Merged a pr for this issue, shouldn't this issue be closed?

**Comment by sneako** [comment]
Yes, thanks!
