### ISSUE TITLE
Automatically terminate pools if unused

### ISSUE THREAD

**Issue by oliveigah** [sneako/finch#159]
Hey, I'm currently looking for tackle this problem that is even explicit on the readme: `Note pools are not automatically terminated if they are unused, so Finch is best suited when you are requesting a known list of static hosts.`

In my first look on the issue I think the right place to start is on nimble pool library it self, right? Since AFAIK it does not support this use case (https://github.com/dashbitco/nimble_pool/issues/1)

I restarted the thread about this problem on `NimblePool` because it is from 2019 and wrote there my initial thoughts about how to solve it.

Is my view of the problem correct? Or can you see another way to implement this?

**Comment by sneako** [comment]
Hi @oliveigah! I haven't thought too much about this issue yet as all of the applications where I use Finch only send out requests to a static list of hosts, but I could see how this feature would be useful, especially in Finch wrappers like Req and Tesla.

I think it could make sense to add this as an optional feature to NimblePool. If there were some option that we could pass to NimblePool which would cause the pool to terminate after a period of inactivity, that would be all that we need. On the Finch side, if we were to send a request for a pool that has already been shutdown, Finch would simply start a new pool, so I don't think any changes would be necessary in this library (besides perhaps some documentation).

However, I believe that https://github.com/dashbitco/nimble_pool/issues/1 is not referring to the pool itself, but rather the resources that it manages, which in our case are the connections.

**Comment by oliveigah** [comment]
HI @sneako , thanks for the insight!

> I could see how this feature would be useful
My use case here is a postbacker, so the client can send me a custom URL and some configuration and my application will send the postback after some time.  Since I have no control of the client's URL would be good to have this feature.

If you see another way I could fit finch in this use case, I would love to hear!

> If there were some option that we could pass to NimblePool which would cause the pool to terminate after a period of inactivity, that would be all that we need.

Gonna share with you what I was worried about:

Terminate the poll while a long connection is running would not be a potential problem?

Terminate a poll without properly terminate the connections (running or not), could be a potential problem? I don't know exactly how Finch wraps Mint, but since it is a processless approach it maybe not an issue.

If you have some highlights on what to look feel free to give more insight about how finch handle the connections, I'll take sometime to study this part of the code as well.

> However, I believe that [dashbitco/nimble_pool#1](https://github.com/dashbitco/nimble_pool/issues/1) is not referring to the pool itself, but rather the resources that it manages, which in our case are the connections.

Totally agree that the issue on NimblePool is about the resources(connections in our case), anyway I think that to properly implement the pool termination logic on NimblePool side, the first step is handle the resources termination because NimblePool may be used for other use cases that the problems of terminating the pool without terminating the resources could be dangerous.

Since NimblePool is a more generic approach to the pool problem, and not only for connections (that may not need handle the connections termination depending on implementation), I think the right way is to implement it first there, what you think? :smiley:

**Comment by sneako** [comment]
Ah yes, you would definitely need this feature if you were to use Finch in this way, in a long running application.

I should also mention that while Mint supports protocol negotiation, Finch cannot. This is due to the fact that we use different pooling strategies for HTTP/1.1 vs HTTP/2. We need to send a request to do ALPN, but we need a pool to send a request, so it is kind of a chicken and egg situation that Finch was not designed to handle.

Since all of your URLs are unknown at the time you start Finch, you will have to choose whether the `:default` pool configuration will use HTTP/1 or HTTP/2. So for example, if you assume that the client will always send you URLs that support HTTP/1, but then they happen to send a URL that only supports HTTP/2 (rare but possible), the requests to that HTTP/2 URL will fail.

Most of the benefits Finch provides come from its pooling strategies which allow it to reuse long lived connections while minimizing copying of memory between processes. If your requests will have large request or response bodies, then you might still see some benefit due to this minimal copying, but otherwise you will probably have an easier time using an alternative HTTP client.

I plan to add a section explaining this to the README so that it is more clear what Finch's design goals were and which use cases it is more suited for.

That said, I am definitely still interested in seeing NimblePool gain the ability to shut down after a configurable idle period.

**Comment by oliveigah** [comment]
Thanks for the great insight @sneako ! :smile: 

> Since all of your URLs are unknown at the time you start Finch, you will have to choose whether the `:default` pool configuration will use HTTP/1 or HTTP/2.

I was thinking about start pools dynamically accordingly with some previous configuration from the client and the default behaviour being HTTP/1. Do you have any considerations regarding starting Finch pools dynamically?

> That said, I am definitely still interested in seeing NimblePool gain the ability to shut down after a configurable idle period.

Great! I'm working on it right now, and when it's done I'll open a PR on Finch to leverage the new feature.

**Comment by sneako** [comment]
My pleasure!

If you can rely on the fact that these servers will always support HTTP/1 then the default pool configuration should work fine.

You could consider decreasing the pool size (the default is 50), but since Finch uses "lazy" NimblePools, connections will only be opened as needed and the pool size acts more like an upper limit to how many connections could be opened in a specific pool, so it shouldn't be necessary.

**Comment by sneako** [comment]
Also, I would like to add, it is very important for Finch that NimblePool stays as fast as possible. Ideally the changes that happen there will have zero impact on the performance of the pool. I suppose it could also be acceptable if there is a small performance hit, but only in the case that the pools are configured to shut down after an idle period, allowing the user to opt out and retain the current level of performance :pray:

**Comment by oliveigah** [comment]
> but only in the case that the pools are configured to shut down after an idle period

That`s exactly how I'm doing it. If the pool does not pass the idle_timeout configuration to NimblePool, it should not have any impact on performance.

> I suppose it could also be acceptable if there is a small performance hit

For now the only impact I'm foreseeing is the periodic timer that will check the resources queue.

For highly active pools the impact might be just a peek on the queue and an if checking last enqueued time for the resource, every tick on the timer. Which in unlikely to severely impact performance, unless the idle timeout is set too low.

The higher impact may be to idle pools, which may executed multiples workers termination, especially with not lazy pools where there is a trade off to be made regarding resources restarts. But since the pools are idle performance might not be a big priority IMO, what you think?

**Comment by sneako** [comment]
Great, that sounds good to me!

**Comment by oliveigah** [comment]
Hey @sneako, the PR implementing idle termination on nimble_pool just got merged (https://github.com/dashbitco/nimble_pool/pull/22), therefore I'm looking for start the Finch side modification (probably just forward 2 new pool configuration options).

Regarding your concern about impacts on performance, do you have any load tests I could execute in order to guarantee there is no performance issue?

**Comment by sneako** [comment]
Great work @oliveigah ! I do have some tests that I can run, but if the Finch changes will just involve forwarding these pool configuration options it might make more sense to benchmark NimblePool itself. Do you agree?

**Comment by oliveigah** [comment]
Yeah, it makes sense to test NimblePool it self, I'm just thinking about how some finch implementations of the pool might interact with the new termination feature.

If you do not use the the new `:worker_idle_timeout` nothing changes.

But if you use it the `terminate_worker/3` callback will be executed for all idle workers each cycle. Therefore the feature is dependent on how your worker is terminated, which is with `Conn.close(conn)` in Finch.

Since I do not have extensive knowledge on mint, idk if a large number of terminations in sequence could have some issue. 

Also this termination can lead to a scenario where a checkout request arrive while the pool is being terminated, in this case the checkout will fail and afaik Finch will not start a new pool. Is this a problematic behaviour in your opinion?

**Comment by sneako** [comment]
Looking more closely at your NimblePool changes and I think you did a great job in taking the performance impact in to consideration.

The only difference a user who has not opted in to idle timeouts will see is a few more calls to `System.monotonic_time/1` which is quite fast. I wonder if it is worth skipping that function call unless we have a `:worker_idle_timeout`? I guess that is something a benchmark could answer.

RE: "large number of terminations in sequence", I don't think we need to worry about that too much. Mint is not doing anything too complicated here, just delegating to `:gen_tcp` or `:ssl`.

RE: pool terminating when a checkout request arrives, that could certainly be annoying, but I suppose that would only really happen if the `:worker_idle_timeout` is misconfigured with a value that is too low for the particular use case.

**Comment by oliveigah** [comment]
Great catch on the `System.monotonic_time/1` I did forget to take it on account.

I've tried to do a quick benchmark to see the impact of this extra call on check-ins, although my measures were quite variant, they were most between 1% ~ 4% of impact on performance.

To put it on numbers, I did 50 checkouts/checkins in a row to a pool with a single worker.

The modified version added 2~4 milliseconds, some examples of the average time to complete 50 checkouts/checkins:
```
unmodified: 129 ms
modified: 133 ms

unmodified: 125 ms
modified: 128 ms

unmodified: 137 ms
modified: 139 ms
```

My benchmark was very naive but indicates some room for improvement for sure, gonna take a look on how I can improve it.

I think the call is not the problem at all, what may be problematic is the additional data that must be moved around.

Gonna try some modifications on the code and see how it performs! Thanks for the feedback! :smile:

**Comment by oliveigah** [comment]
Great catch on the System.monotonic_time/1 I did forget to take it on account.

I did a quick benchmark to see the impact of the new feature on checkouts/checkins (the most sensible part to this change IMO), although my measures were quite variant, they were most between 5% ~ 10% of impact on performance. This impact might be composed by the call it self, the data transfer overhead and the extra conditionals.

This means at most 0.5~1 extra microseconds on each checkin due to the ping implementation. This benchmark is definitely not conclusive but indicates some room for improvement, although 1 extra microsecond is quite acceptable IMO.

```
Benchmark results:

A is the avg time to checkout an worker on the unmodified instance of nimble pool (without my contribution)
B is the avg time to checkout an worker on the modified instance of nimble pool (with my contribution)

Both A and B are lazy pools with only 1 worker. I did 100 checkouts in a row and calculate the avg time to complete a checkout.

[
  %{A: 4.9, B: 5.09, dif: "3.96%"},
  %{A: 4.18, B: 4.59, dif: "9.67%"},
  %{A: 4.17, B: 4.53, dif: "8.55%"},
  %{A: 3.44, B: 3.56, dif: "3.5%"},
  %{A: 4.56, B: 4.62, dif: "1.37%"},
  %{A: 5.45, B: 5.53, dif: "1.44%"},
  %{A: 5.54, B: 6.07, dif: "9.67%"},
  %{A: 4.75, B: 4.95, dif: "4.26%"},
  %{A: 4.68, B: 5.06, dif: "7.95%"},
  %{A: 2.93, B: 3.14, dif: "7.45%"}
]
```

Gonna check tomorrow if your suggestion to only call `System.monotonic_time/1` if the ping option is implemented improves the solution! Thanks for the feedback  :smile:

**Comment by oliveigah** [comment]
Just to add info, I've executed the same benchmark comparing A x A and B x B, just to see the normal fluctuation between iterations and the results are:

```
A x A: (unmodified x unmodified)
[
  %{A1: 6.1, A2: 5.89, dif: "-3.42%"},
  %{A1: 5.08, A2: 5.15, dif: "1.43%"},
  %{A1: 3.81, A2: 3.86, dif: "1.32%"},
  %{A1: 3.52, A2: 3.57, dif: "1.38%"},
  %{A1: 2.84, A2: 2.86, dif: "0.58%"},
  %{A1: 3.43, A2: 3.43, dif: "0.28%"},
  %{A1: 3.34, A2: 3.41, dif: "2.18%"},
  %{A1: 3.37, A2: 3.32, dif: "-1.5%"},
  %{A1: 5.03, A2: 5.22, dif: "3.76%"},
  %{A1: 4.06, A2: 4.23, dif: "4.23%"}
]

B X B (modified x modified)
[
  %{B1: 6.04, B2: 6.09, dif: "0.9%"},
  %{B1: 7.82, B2: 7.67, dif: "-1.87%"},
  %{B1: 3.9, B2: 3.89, dif: "-0.26%"},
  %{B1: 4.03, B2: 3.89, dif: "-3.41%"},
  %{B1: 4.59, B2: 4.68, dif: "1.89%"},
  %{B1: 3.12, B2: 3.18, dif: "2.1%"},
  %{B1: 3.4, B2: 3.5, dif: "3.07%"},
  %{B1: 4.44, B2: 4.42, dif: "-0.42%"},
  %{B1: 3.39, B2: 3.27, dif: "-3.34%"},
  %{B1: 4.16, B2: 4.03, dif: "-3.2%"}
]
```

By this result we can see the normal fluctuation is 2~3%. 

Also if you want to see how I did this benchmark to suggest some improvements or verify the results here is the gist: https://gist.github.com/oliveigah/1f619232a4e0212094d40edab77fce69

**Comment by oliveigah** [comment]
Sorry for the delay, got dragged by some work stuff.

Gonna benchmark your suggested change on the next days.

**Comment by oliveigah** [comment]
Hey @sneako, just did the modification to only call `System.monotonic_time/1` if `:worker_idle_timeout` is defined. The benchmark improved a bit but the code seems more complicated to me because it must consider one more parameter in order to initialize and enqueue workers.

IMO, the clarity tradeoff is not worth it. To achieve a clearer solution I gonna need to do some refactor on the implementation. If this performance impact is a deal breaker to you I could consider refactor the solution on nimble pool next month, let me know what you think! :smiley:  

```
[
  %{A: 15.23, B: 15.07, dif: "-1.03%"},
  %{A: 14.48, B: 14.56, dif: "0.57%"},
  %{A: 14.97, B: 15.35, dif: "2.58%"},
  %{A: 15.85, B: 15.81, dif: "-0.25%"},
  %{A: 13.95, B: 13.89, dif: "-0.43%"},
  %{A: 7.81, B: 8.1, dif: "3.6%"},
  %{A: 16.45, B: 16.78, dif: "2.0%"},
  %{A: 10.87, B: 11.17, dif: "2.75%"},
  %{A: 14.43, B: 14.58, dif: "1.01%"},
  %{A: 10.69, B: 11.17, dif: "4.47%"}
]
```

**Comment by sneako** [comment]
Thanks @oliveigah. I can try running my more thorough benchmarks when I have a bit of free time to see how these pool changes affect Finch's overall performance. Hopefully making the pool just a tiny bit slower will not be noticeable. I am slightly concerned because at work we are really pushing Finch HTTP/1 pools to their limits, and we do see a consistent (albeit very low) rate of pool timeouts which I would like to eliminate rather than make slightly worse.

**Comment by oliveigah** [comment]
Got it! Let me know what you find on your benchmark.

Gonna try to work on a better implementation on the nimble pool side asap, so you do not need to run your benchmarks twice.

**Comment by sneako** [comment]
No rush!

For best results, the benchmark should be run across multiple machines. Usually I use a pair of decently sized ec2 instances, a client and a server, which requires a paid AWS account.

I ran these tests very frequently when we started working on Finch which was over a year ago at this point, so there is quite a bit to update before we can use them again. It is a fork of a fork that I have hacked to suit my needs. I will get them updated and running again so that we can properly test these new changes.

**Comment by oliveigah** [comment]
Just pinging about the tests regarding the usage of the new feature of nimble pool.

Can I help you with something @sneako?

If you provide some high level instructions about how would you do these tests I could run it my self on some cloud instances too, no worries! Just let me know! 😄

**Comment by oliveigah** [comment]
Don't worry! I indeed left you here waiting for the new implementation of the feature on nimble pool. Totally forgot I would do that, my bad. 😅

Gonna work on something that does not call `System.monotonic_time/1` unnecessarily and run your tests for both implementations to see the difference.

**Comment by oliveigah** [comment]
@sneako, after read the code again I've found a much clearer way to make the change you proposed. (Take some time off really helps. haha :sweat_smile: )

I just opened the PR, but now I think the change will be completely transparent for users that do not want to use the new feature. Let me know what you think!

**Comment by sneako** [comment]
That looks perfect! With this change in place, I don't think there is any need to fiddle with these load tests.

**Comment by oliveigah** [comment]
With the release of the nimble pool v0.2.5 which includes the optimized version of the feature, I'm looking forward to work on the implementation on the finch side.

On my first look at the code I guess the approach will be:

- Add "pool_max_idle_time" to pool config schema
- Forward "pool_max_idle_time" to `Finch.HTTP1.Pool` initialization on `Finch.PoolManager.do_start_pools/2`
- Implement handle_ping/2 on `Finch.HTTP1.Pool` which will return `{:stop, user_reason}` which will call NimblePool `terminate_worker/3` callback for each connection on the pool.

Finally I have a couple questions:

- Do you think it makes sense to let the user provide a custom implementation for `handle_ping/2` or should we provide a default behaviour of terminating the pool after some idle time?

- Regarding tests, do you think makes sense to add tests about pool termination after idle timeout? Or the nimble pool tests are enough to we rely on?

**Comment by sneako** [comment]
The approach you described sounds good to me!

I don't think we need to allow for custom implementations of `handle_ping/2`. Was there a specific use case you had in mind?

The NimblePool tests are great, but I still think we should try to add at least one test for pool termination on our end too.

**Comment by oliveigah** [comment]
> Was there a specific use case you had in mind?

I was thinking about if the user wants to run some custom code like notification or some other cleanup unrelated to connections when the pool gets terminated but after some thought I think there is better ways to achieve it outside finch it self with monitors and links.

Gonna go with the default behaviour and if some use case to a custom implementation arises we can modify it later.

> but I still think we should try to add at least one test for pool termination on our end too.

Great, gonna add some tests on the finch side too!

**Comment by sneako** [comment]
For a notification of pool termination, that sounds like a job for telemetry to me. Let’s make sure we add an event for that. Great call!

**Comment by oliveigah** [comment]
Found a bug on nimble_pool while implementing the feature here! :disappointed: 

https://github.com/dashbitco/nimble_pool/pull/26

Gonna finish the implementation after it being resolved.

**Comment by alexandremcosta** [comment]
Should this be closed?

**Comment by sneako** [comment]
Yes, thanks @alexandremcosta !
