### ISSUE TITLE
Test failures with Elixir 1.13.0-rc.0

### ISSUE THREAD

**Issue by marcandre** [sneako/finch#162]
Running the test suite from the repo (tag v0.9.1) gives me no failure with elixir 1.12 but with elixir 1.13.0-rc.0 I get 10 failures.

<details>
  1) test request/3 successful post streaming request, with streaming body and query string (FinchTest)
     test/finch_test.exs:219
     match (=) failed
     The following variables were pinned:
       response_body = "{\"right\":\"here\"}"
     code:  assert {:ok, %Response{status: 200, headers: headers, body: ^response_body}} = Finch.build(:post, endpoint(bypass, "?" <> query_string), [{header_key, header_val}], {:stream, req_stream}) |> Finch.request(finch_name())
     left:  {:ok, %Finch.Response{body: ^response_body, headers: headers, status: 200}}
     right: {:ok, %Finch.Response{body: "", headers: [{"connection", "close"}, {"content-length", "0"}], status: 400}}
     stacktrace:
       test/finch_test.exs:240: (test)

....

  2) test request/3 successful get request, with query string, when given a %URI{} (FinchTest)
     test/finch_test.exs:256
     match (=) failed
     code:  assert {:ok, %{status: 200}} = Finch.build(:get, uri) |> Finch.request(finch_name())
     left:  {:ok, %{status: 200}}
     right: {:ok, %Finch.Response{status: 400, body: "", headers: [{"connection", "close"}, {"content-length", "0"}]}}
     stacktrace:
       test/finch_test.exs:266: (test)

....

  3) test stream/5 successful post request, with query string and streaming request body (FinchTest)
     test/finch_test.exs:756
     match (=) failed
     The following variables were pinned:
       resp_body = "{hi:\"there\"}"
     code:  assert {:ok, {200, [_ | _], ^resp_body}} = Finch.build(:post,
            endpoint(bypass, "?" <> query_string),
            req_headers,
            {:stream, req_stream}) |> Finch.stream(finch_name(), acc, fun)
     left:  {:ok, {200, [_ | _], ^resp_body}}
     right: {:ok, {400, [{"connection", "close"}, {"content-length", "0"}], ""}}
     stacktrace:
       test/finch_test.exs:778: (test)

.....

  4) test request/3 successful post request, with body and query string (FinchTest)
     test/finch_test.exs:185
     match (=) failed
     The following variables were pinned:
       response_body = "{\"right\":\"here\"}"
     code:  assert {:ok, %Response{status: 200, headers: headers, body: ^response_body}} = Finch.build(:post,
            endpoint(bypass, "?" <> query_string),
            [{header_key, header_val}],
            req_body) |> Finch.request(finch_name())
     left:  {:ok, %Finch.Response{body: ^response_body, headers: headers, status: 200}}
     right: {:ok, %Finch.Response{body: "", headers: [{"connection", "close"}, {"content-length", "0"}], status: 400}}
     stacktrace:
       test/finch_test.exs:203: (test)

.

  5) test request/3 successful get request, with query string (FinchTest)
     test/finch_test.exs:171
     match (=) failed
     code:  assert {:ok, %{status: 200}} = Finch.build(:get, endpoint(bypass, "?" <> query_string)) |> Finch.request(finch_name())
     left:  {:ok, %{status: 200}}
     right: {:ok, %Finch.Response{status: 400, body: "", headers: [{"connection", "close"}, {"content-length", "0"}]}}
     stacktrace:
       test/finch_test.exs:180: (test)

....

  6) test stream/5 successful post request, with query string and string request body (FinchTest)
     test/finch_test.exs:731
     match (=) failed
     The following variables were pinned:
       resp_body = "{hi:\"there\"}"
     code:  assert {:ok, {200, [_ | _], ^resp_body}} = Finch.build(:post, endpoint(bypass, "?" <> query_string), req_headers, req_body) |> Finch.stream(finch_name(), acc, fun)
     left:  {:ok, {200, [_ | _], ^resp_body}}
     right: {:ok, {400, [{"connection", "close"}, {"content-length", "0"}], ""}}
     stacktrace:
       test/finch_test.exs:751: (test)

......

  7) test stream/5 successful get request, with query string (FinchTest)
     test/finch_test.exs:709
     match (=) failed
     code:  assert {:ok, {200, [_ | _], "OK"}} = Finch.build(:get, endpoint(bypass, "?" <> query_string)) |> Finch.stream(finch_name(), acc, fun)
     left:  {:ok, {200, [_ | _], "OK"}}
     right: {:ok, {400, [{"connection", "close"}, {"content-length", "0"}], ""}}
     stacktrace:
       test/finch_test.exs:726: (test)

.........

  8) test cancel streaming response (Finch.HTTP2.IntegrationTest)
     test/finch/http2/integration_test.exs:135
     Expected to catch throw, got nothing
     code: assert catch_throw(
     stacktrace:
       test/finch/http2/integration_test.exs:151: (test)

     The following output was logged:

     21:43:27.613 [warning] Description: 'Authenticity is not established by certificate path validation'
          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

  9) test sends http2 requests (Finch.HTTP2.IntegrationTest)
     test/finch/http2/integration_test.exs:17
     match (=) failed
     code:  assert {:ok, response} = Finch.build(:get, url) |> Finch.request(TestFinch)
     left:  {:ok, response}
     right: {:error, %Mint.HTTPError{module: Mint.HTTP2, reason: {:server_closed_request, :protocol_error}}}
     stacktrace:
       test/finch/http2/integration_test.exs:34: (test)

     The following output was logged:

     21:43:27.660 [warning] Description: 'Authenticity is not established by certificate path validation'
          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

     21:43:27.661 [warning] Description: 'Authenticity is not established by certificate path validation'
          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

     21:43:27.661 [warning] Description: 'Authenticity is not established by certificate path validation'
          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

     21:43:27.661 [warning] Description: 'Authenticity is not established by certificate path validation'
          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

     21:43:27.661 [warning] Description: 'Authenticity is not established by certificate path validation'
          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

 10) test writes TLS secrets to SSLKEYLOGFILE file (Finch.HTTP2.IntegrationTest)
     test/finch/http2/integration_test.exs:102
     match (=) failed
     code:  assert {:ok, response} = Finch.build(:get, url) |> Finch.request(TestFinch)
     left:  {:ok, response}
     right: {:error, %Mint.HTTPError{module: Mint.HTTP2, reason: {:server_closed_request, :protocol_error}}}
     stacktrace:
       test/finch/http2/integration_test.exs:126: (test)

     The following output was logged:

     21:43:27.678 [warning] Description: 'Authenticity is not established by certificate path validation'
          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

     21:43:27.679 [warning] Description: 'Authenticity is not established by certificate path validation'
          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

     21:43:27.679 [warning] Description: 'Authenticity is not established by certificate path validation'
          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

     21:43:27.679 [warning] Description: 'Authenticity is not established by certificate path validation'
          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

     21:43:27.680 [warning] Description: 'Authenticity is not established by certificate path validation'
          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

......

Finished in 3.4 seconds (1.7s async, 1.6s sync)
49 tests, 10 failures

Randomized with seed 405297
</details>

**Comment by marcandre** [comment]
FYI, tests for `exvcr` also fail only in Elixir 1.13, and only for the `finch` adapter, which led me to run `finch`'s test suite.

**Comment by sneako** [comment]
Thank you for reporting! I can confirm that there are many failures, mostly in the tests that use Bypass, when running `1.13.0-rc.0-otp-24`.

Luckily, `1.13.0-rc.1-otp-24` seems to fix the problem!

**Comment by marcandre** [comment]
Those are the best bug fixes ever 🎉
Thanks for looking into it.
