### ISSUE TITLE
IPv6 Documentation

### ISSUE THREAD

**Issue by ericsullivan** [sneako/finch#163]
I was recently setting up an application on Fly.io
I wanted to use the internal 6PN DNS to communicate with a backend service. [REF](https://fly.io/blog/ipv6-wireguard-peering/#6pn-dns)
It did not work with the default settings in Finch / Mint (but HTTPoison worked, so I assumed it was a library configuration issue). It took a bit of digging, but I found this option:
https://github.com/elixir-mint/mint/blob/main/lib/mint/core/transport/tcp.ex#L22
`inet6`

It was not documented in the transport options though:
https://hexdocs.pm/mint/Mint.HTTP.html#connect/4-transport-options

(I'll be submitting a PR for that shortly)

The solution in Finch was to add it to the pools configuration:

```
pools: %{
  default: [
    conn_opts: [
      transport_opts: [inet6: true]
    ]
  ]
}
```

I'm not sure if this is a significant enough issue to mention it in the Finch documentation, but it was a bit hard to track down and I wanted to at least open a searchable issue. Thank you

**Comment by sneako** [comment]
Sorry for the delay! I agree with Eric on this one. Having this issue definitely helps, thanks for creating it!
