### ISSUE TITLE
Issue when duplicate content-type headers exists 

### ISSUE THREAD

**Issue by epinault** [sneako/finch#170]
I am using Tesla and it has a middleware that adds the content-type for json. But adding if I add to the headers manually the content-type again, it can appears twice. Seems that Finch does not handle it and I see some side effect . I am not sure if this is an expected behavior but I would have not expected it to fail at all

here is an example of a success request

```
 Finch.request(:pool_name, :post, "http://localhost:2004/graphql", [ {"content-type", "application/json" }], Jason.encode!(body))
```

here is one that will fail

```
 Finch.request(:pool_name, :post, "http://localhost:2004/graphql", [{"content-type", "application/json" }, {"content-type", "application/json" }], Jason.encode!(body))
 ```

that duplicate headers causes an error response like

```
"{\"errors\":[{\"locations\":[{\"column\":2,\"line\":1}],\"message\":\"syntax error before: \\\"\\\\\\\"query\\\\\\\"\\\"\"}]}",
```

not sure if this is a client issue or also a Phoenix issue. But merging the headers before making the request would be safe

**Comment by sneako** [comment]
Hi @epinault !

According to the [HTTP spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) "Multiple message-header fields with the same field-name MAY be present in a message...".

Finch's main goal is performance, so validating/merging the headers before sending the request is not something that I would be interested in adding to this library. In fact, I have even considered starting a discussion with the Mint team around making the lower-casing of header keys optional somehow.

I am guessing that you are using Absinthe for GraphQL, and it appears that Absinthe does not like to receive duplicate headers (at least the for `content-type`). I tried sending a request with duplicate `content-type` headers to a plain Phoenix server and it handled the duplicate headers just fine.

I suppose the error messaging could be improved within Absinthe, but I think the best solution in this case is to avoid adding the header twice.

I'll leave this issue open for now in case you have any follow up questions.

**Comment by epinault** [comment]
yea that makes sense! thanks for looking at this so quickly ❤️ . Did you file an issue for absinthe: otherwise happy to file one for them . I did not think to try without absinthe and was not expecting it . Awesome find!

we are fixing our wrapper to not add the extra header (we are using Tesla so had to try different layer to see it happen)

**Comment by epinault** [comment]
Based on the answer from the Absinthe project, it seems that actually it s not correct and should be handled by the client really. Reading the spec seems to also imply that having multiple is for a specific reason (if they are different) and multiple values

**Comment by sneako** [comment]
The wording is a bit confusing as I too had the same interpretation as Ben when I first read it. I think this stackoverflow post explains it pretty well https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable

Either way, as as user of Finch it is going to be your responsibility to build the request that you want to send. Even curl has the same behaviour:

```
$ curl -H 'content-type: text' -H 'content-type: html' http://example.com -v       
*   Trying 93.184.216.34:80...
* Connected to example.com (93.184.216.34) port 80 (#0)
> GET / HTTP/1.1
> Host: example.com
> User-Agent: curl/7.79.1
> Accept: */*
> content-type: text
> content-type: html
```
