### ISSUE TITLE
new unified telemetry event 

### ISSUE THREAD

**Issue by dvic** [sneako/finch#175]
I'm working on an OpenTelemetry library but I'm encountering some difficulties in the implementation while trying to capture various kinds of errors (e.g., `nxdomain` in the connect step). The underlying issue here is that there is no guaranteed 'start' and 'end' event when a request is executed in Finch. It requires a lot of error prone checks and edge-case handling to get it right. 

Would it make sense to emit a new set of telemetry events `[:finch, :execute_request, :start | :stop | :exception]` or just simply the `[:finch, :request_executed]` event? (with duration as measurement) This new event would basically wrap `request/3`.

**Comment by dvic** [comment]
related discussion: https://github.com/wojtekmach/req/issues/87

**Comment by dvic** [comment]
> I think we would probably want to do this in `stream/5` rather than `request/3` since request calls stream anyway, and that way both public API functions would be covered.

Agreed.

> I think we should probably go with the first option you presented, emitting the full set of events `:start | :stop | :exception`.

👍

> I am not crazy about the name `:execute_request` because we already have `:request` and having both seems like it could cause confusion. The only other idea for a name I have at this moment is to call it `:stream` since this will be executed in the stream function and there aren't any other events that `:stream` could be confused with, what do you think? I am open to suggestions.

Yeah I was thinking the same. I think your suggestion to use  `:stream` instead makes sense actually, it relates directly to the function that's emitting it :).

I'll submit a PR to get things going and then we can take it from there.

**Comment by sneako** [comment]
Thanks for your input @keathley ! You do make a good point, `stream` could be confusing. Maybe I was too concerned with minimizing breaking changes.

If we go with `:request` then we need to pick a new name for the existing `request` event. Maybe we should replace the `request` with `send` and replace `response` with `recv` like the Linux socket api?

**Comment by dvic** [comment]
> If we go with `:request` then we need to pick a new name for the existing `request` event. Maybe we should replace the `request` with `send` and replace `response` with `recv` like the Linux socket api?

I think this is a good idea, but given https://github.com/sneako/finch/pull/176#discussion_r845203482, do we still want a separate `:stream` event? We would have a `:request` event with `:result` and a `:stream` event with `:acc`, to semantically indicate the difference between the two?

**Comment by sneako** [comment]
Hey @dvic and sorry for the delay! I don't really see any value in adding the extra event, ie `stream/5` emits `:stream` and `request/3` emits both `:request` and `:stream` if that is what you meant.

The approach in your latest commit seems like it should be fine if we change the name to `:request`. Unfortunately, if we go with `:request` for the name, there isn't really a way to gracefully deprecate the existing events. That is probably fine since we are still pre-1.0.

If we go that route, then we could probably skip https://github.com/sneako/finch/pull/177 and instead switch `:error` and `:reason` at the same time while providing a short upgrade guide for users. What do you think?

**Comment by dvic** [comment]
> Hey @dvic and sorry for the delay! I don't really see any value in adding the extra event, ie `stream/5` emits `:stream` and `request/3` emits both `:request` and `:stream` if that is what you meant.
> 
> The approach in your latest commit seems like it should be fine if we change the name to `:request`. Unfortunately, if we go with `:request` for the name, there isn't really a way to gracefully deprecate the existing events. That is probably fine since we are still pre-1.0.
> 
> If we go that route, then we could probably skip #177 and instead switch `:error` and `:reason` at the same time while providing a short upgrade guide for users. What do you think?

I'm fine going with this route, it's indeed pre-1.0 and I think this is a sensible breaking change. Shall I update the PR and switch the current `request` and `response` events to `send` and `recv`, like you suggested? (I liked that idea)

**Comment by sneako** [comment]
Sounds good to me, let's do it! Thanks :)

**Comment by dvic** [comment]
I've just pushed to #176, let me know if there's anything else 👍
