### ISSUE TITLE
introduce a 'private' Finch.Request  field for libraries built on top of Finch

### ISSUE THREAD

**Issue by dvic** [sneako/finch#179]
It would be nice if the OpenTelemetry library for Finch I'm building can support custom span names, e.g., `GET /users/:id` instead of the standard HTTP GET name (see https://github.com/ricardoccpaiva/opentelemetry_tesla/pull/17#issuecomment-1090781681). However, this would require the user to pass in the custom span name per request so that this info can be extracted when I'm consuming the telemetry events and creating the OpenTelemetry spans.

What do you think about adding a field called private in the Finch.Request struct to support this and other usecases?

This is how it would work (for example)

```elixir
Finch.build(:get, "https://example.com/users/123")
|> OpentelemetryFinch.span_details("/users/:user_id", user_id: 123)
|> Finch.request(MyFinch)
```

**Comment by sneako** [comment]
Adding a `:private` map field to the Request struct sounds good to me! PR is welcome, thank you

**Comment by wojtekmach** [comment]
> ```elixir
> Finch.build(:get, "https://example.com/users/123")
> |> OpentelemetryFinch.span_details("/users/:user_id", user_id: 123)
> |> Finch.request(MyFinch)
> ```

out of curiosity, is this the whole snippet? Nothing shown here seems to read from `request.private`. Is there another function that the request would be passed to?

**Comment by sneako** [comment]
> > ```elixir
> > Finch.build(:get, "https://example.com/users/123")
> > |> OpentelemetryFinch.span_details("/users/:user_id", user_id: 123)
> > |> Finch.request(MyFinch)
> > ```
> 
> out of curiosity, is this the whole snippet? Nothing shown here seems to read from `request.private`. Is there another function that the request would be passed to?

My understanding was that `OpenTelemetrtyFinch` would provide `:telemetry` handlers and in these handlers the private field would be accessed.

Perhaps you are suggesting that we should also provide a `get_private/2` function?

**Comment by wojtekmach** [comment]
Oh, of course, the request struct is sent in the events, that makes sense. Regarding `get_private`, I wasn't thinking about adding it but wouldnt oppose it. I think Plug.Conn has it too.

**Comment by dvic** [comment]
> Oh, of course, the request struct is sent in the events, that makes sense.

Exactly, that's the idea :)

> Regarding `get_private`, I wasn't thinking about adding it but wouldnt oppose it. I think Plug.Conn has it too.

I just checked, it has only `merge_private/2`, no `get_private/2`.
