### ISSUE TITLE
Finch.stream/5 crashes

### ISSUE THREAD

**Issue by alexcastano** [sneako/finch#192]
Hello!

The following code crashes:

```
iex(1)> fun = fn _msg, :ok -> :ok end
#Function<43.65746770/2 in :erl_eval.expr/5>
iex(1)> Finch.build(:get, "https://elixir-lang.org/") |> Finch.stream(MyFinch, :ok, fun)
** (CaseClauseError) no case clause matching: {:ok, %Mint.HTTP1{buffer: "", host: "elixir-lang.org", mode: :passive, port: 443, private: %{}, proxy_headers: [], request: nil, requests: {[], []}, scheme_as_string: "https", socket: {:sslsocket, {:gen_tcp, #Port<0.24>, :tls_connection, :undefined}, [#PID<0.977.0>, #PID<0.976.0>]}, state: :open, streaming_request: nil, transport: Mint.Core.Transport.SSL}, :ok}
    (finch 0.11.0) lib/finch/http1/conn.ex:178: Finch.Conn.handle_response/5
    (finch 0.11.0) lib/finch/http1/conn.ex:122: Finch.Conn.request/6
    (finch 0.11.0) lib/finch/http1/pool.ex:50: anonymous fn/8 in Finch.HTTP1.Pool.request/5
    (nimble_pool 0.2.6) lib/nimble_pool.ex:349: NimblePool.checkout!/4
    (finch 0.11.0) lib/finch/http1/pool.ex:43: Finch.HTTP1.Pool.request/5
```

The code expects that the stream function returns `{status, header, body}`. I saw that the `request/3` reuses the stream function and it uses this tuple. I guess this is the origin of the problem. I can help if you want, but I don't know how do you want to solve the problem.

Thank you for your time

**Comment by sneako** [comment]
Thanks for opening this issue! We made some improvements to our Telemetry events recently, and unfortunately it appears that one of those changes included an implicit assumption about the shape of the accumulator that is used in the stream function, here: https://github.com/sneako/finch/blob/main/lib/finch/http1/conn.ex#L172

I think we probably have to change this back to:

```diff
-      {:ok, mint, {status, headers, _} = acc} ->
+      {:ok, mint, acc} ->
-        metadata = Map.merge(metadata, %{status: status, headers: headers})
```
It would be nice to have access to the status and headers in the `[:finch, :recv, :stop]` event, but users will have to rely on the `:result` field of the `[:finch, :request, :stop]` instead.

**Comment by dvic** [comment]
Oops, sorry about that!

We could emit separate telemetry events here to have the status and headers inside stream events: https://github.com/sneako/finch/blob/main/lib/finch/http1/conn.ex#L196-L200.

**Comment by sneako** [comment]
No worries @dvic! That feels a bit like overkill to me since we already have the full response/accumulator available in the `[:finch, :request, :stop]` event anyway. If a user really needs to be able to access these fields before the request finishes or in the case of an error/exception, they could write a custom stream function in order to do so. What do you think?

**Comment by dvic** [comment]
> No worries @dvic! That feels a bit like overkill to me since we already have the full response/accumulator available in the `[:finch, :request, :stop]` event anyway. If a user really needs to be able to access these fields before the request finishes or in the case of an error/exception, they could write a custom stream function in order to do so. What do you think?

True! But it still feels a bit weird not to have "natively" the status and header fields inside the telemetry metadata. In this way, when a user dus a custom stream function, how would my OpenTelemetry library set the `http.status_code` field of the span? It would require the accumulator function to adhere to return the status right? 

Maybe we can refactor `receive_response` to return the status and headers and it to the meta? It would require a "wrapper" around the reducer function though, so it might impact the performance in a negative way...
