### ISSUE TITLE
Add Finch instance name to connect telemetry

### ISSUE THREAD

**Issue by aselder** [sneako/finch#199]
I'd like to be able to instrument connects from my finch instances. The various connect telemetry events don't expose the pool ID or Finch instance. I'd love to see this added to the meta data so that I can tag the stats I'm collecting by Finch instance and pool.

**Comment by aselder** [comment]
Also, would love to see this added to the queue events as well.

**Comment by sneako** [comment]
> Also, would love to see this added to the queue events as well.

Ideally we can add it to all events :pray:

**Comment by sneako** [comment]
resolved in #252
