### ISSUE TITLE
Feature Request: Adjust HTTP/2 log levels to reduce extra noise

### ISSUE THREAD

**Issue by aselder** [sneako/finch#214]
Several events that happen down in the HTTP2 pool call `Logger.error` when they occur, including times when they will be automatically retried.

Most major exception trackers (Sentry, etc) have mechanism to look for log level or a particular level or higher. Customarily, this level defaults to `:error`. 

I'd love to be able to cut down the log level inside Finch, so these log message won't interfere with our error tracking.

**Comment by HarshBalyan** [comment]
@sneako can you assign this to me?
I would like to work on this.

Reiterating my understanding.

We want to support a config `log_level` which would indicate the minimum level for any log. Anything logged by finch has to be at that level or above.
e.g. `log_level: :error` would allow only `:error`, `:critical`, `:alert` and `:emergency` level logs to be emitted.

**Comment by aselder** [comment]
I was more thinking changing the level the message was recorded at.. so I could make that message a warning instead of an error.

**Comment by HarshBalyan** [comment]
@aselder can you elaborate?
Finch logs at different levels for different use cases(I can see error and warning).
How can we make that configurable at a package level?

**Comment by sneako** [comment]
I think the original title of the issue was a bit confusing so I have updated it. I agree with @aselder, rather than passing in a desired log level to Finch, we can switch the error logs in the HTTP/2 pool in cases where the action will be retried, to warnings.
