### ISSUE TITLE
Feature request: Finch.stream

### ISSUE THREAD

**Issue by hissssst** [sneako/finch#225]
Function which returns `Stream` of a body of the request like
```elixir
request
|> Finch.stream!()
|> Enum.take(10)

[
  {:status_code, code},
  {:headers, headers},
  {:headers, headers},
  ...,
  {:body, body},
  {:body, body},
  {:body, body}
]
```

I've digged into codebase and found out that this would not be possible without patching NimblePool. Here is the corresponding issue https://github.com/dashbitco/nimble_pool/issues/31.

**Comment by sneako** [comment]
Thanks, we have an active discussion happening in #208 feel free to join in
