### ISSUE TITLE
Add an example of downloading a large file using Finch

### ISSUE THREAD

**Issue by mrdotb** [sneako/finch#226]
Hello,

I recently had to download a large zip file using Finch and thought it might be helpful to have an example in the documentation. I came up with the following code snippet:
```elixir
path = "/tmp/big-file.zip"
file = File.open!(path, [:write, :exclusive])
url = "https://domain.com/url/big-file.zip"
request = Finch.build(:get, url)

Finch.stream(request, App.Finch, nil, fn
  {:status, status}, _ ->
    IO.inspect("Download assets status: #{status}")

  {:headers, headers}, _ ->
    IO.inspect("Download assets headers: #{inspect(headers)}")

  {:data, data}, _ ->
    IO.binwrite(file, data)
end)

File.close(file)
```
Thanks !

**Comment by sneako** [comment]
Thanks! I guess I assumed the implementation of `Finch.request/3` was a good enough example of how to stream, but since that is completely hidden in the docs, an example similar to this would be a welcome addition to the `Finch.stream/5` docs

**Comment by sneako** [comment]
Closed via https://github.com/sneako/finch/pull/230
