### ISSUE TITLE
Is it possible to bypass SSL verification?

### ISSUE THREAD

**Issue by thbar** [sneako/finch#253]
With Finch, is there a way (as a last resort in some dirty integration cases) to skip SSL verifications, like when using `curl -k`?

In particular, broken setups like SSL on top of IPs not registered in the cert, or self-signed certificates, are of particular interest to me :-)

I have done a quick bit of research and I am unsure if it is possible or not, especially after reading:
- https://github.com/sneako/finch/issues/178#issuecomment-1094347707

Thanks to anyone able to shed some light on this!

**Comment by wojtekmach** [comment]
```elixir
{:ok, _} = Finch.start_link(name: :insecure, pools: %{default: [conn_opts: [transport_opts: [verify: :verify_none]]]})
{:ok, _} = Finch.build(:get, "https://github.com") |> Finch.request(:insecure)
```

**Comment by sneako** [comment]
Thanks for the example @wojtekmach !

**Comment by thbar** [comment]
Thank you @wojtekmach indeed! Much appreciated :-)
