### ISSUE TITLE
Mint.HTTP1 leaks socket upon receive timeout

### ISSUE THREAD

**Issue by fercasgal** [sneako/finch#254]
When there's a receive timeout, the Mint.HTTP1 simply does:

  defp handle_error(conn, error) do
    conn = put_in(conn.state, :closed)
    {:error, conn, error, []}
  end

But the socket is still open and the calling code has no chance of closing it, since:
  def close(%__MODULE__{state: :closed} = conn) do
    {:ok, conn}
  end

So the calling code believes that it has to open a new connection, and the previous one leaks.

**Comment by sneako** [comment]
Thanks for reporting!
