### ISSUE TITLE
Dialyzer type error

### ISSUE THREAD

**Issue by andyleclair** [sneako/finch#258]
Hello! I believe that from version `0.16` to `0.17` a type error was introduced. Previously, `:infinity` was a valid option for, say, `:pool_timeout` but as of `0.17` the type was set to `pos_integer` (https://github.com/sneako/finch/blob/main/lib/finch.ex#L107)

I can confirm that I don't get dialyzer errors in `0.16` but I do in `0.17`

**Comment by sneako** [comment]
Ah thank you for the report! The correct type should be `timeout()` rather than `pos_integer()` PRs are welcome :pray:

**Comment by sneako** [comment]
resolved in #259
