### ISSUE TITLE
Finch Pool Status when Configuring multiple protocols

### ISSUE THREAD

**Issue by mathieurousseau** [sneako/finch#280]
Hello,

I was reading the doc on the new `Finch.get_pool_status`.
It returns only a possible one of: 
```elixir
{:ok, [[Finch.HTTP1.PoolMetrics.t](https://hexdocs.pm/finch/Finch.HTTP1.PoolMetrics.html#t:t/0)()]}
  | {:ok, [[Finch.HTTP2.PoolMetrics.t](https://hexdocs.pm/finch/Finch.HTTP2.PoolMetrics.html#t:t/0)()]}
  | {:error, :not_found}
``` 

I then configured my pool to be able to use `:http1` and `:http2` in the list of protocols. 

This seems to be conflicting to be able to configure `:http1` and `:http2` for a pool but only return either `:http1` or `:http2` in `Finch.get_pool_status`.

I am sure I am missing something 😅 

Thanks!

**Comment by sneako** [comment]
That's a good point! 

Protocols are a list, and you can certainly configure h1 or h2 to be used for a given URL, therefore `get_pol_status/1` for that URL should certainly be able to return both types of PoolMetrics. 

This sounds like an oversight during the implementation.

I can dig in a bit more later, but do you mind sharing what `Finch.get_pool_status/1` returned in this case?

**Comment by sneako** [comment]
Thinking about this a bit more though, is it even possible for a server to listen for h1 & h2 on the same port? I don't think so, therefore, you should only end up with either an h1 pool or an h2 pool, meaning the documented spec should be correct, right?

**Comment by mathieurousseau** [comment]
It returns :http1 when both are present. 

Interesting, we have been switching between 1 and 2 for some our provider endpoints and their server seemed to handle both 🤔

**Comment by sneako** [comment]
Hm yeah I take it back, some servers might handle both protocols over the same port, but finch should negotiate the protocol and stick to that single protocol. 
I don't think there could be a situation where Finch opens some h1 connections AND some h2 connections to the same scheme, host, port combination simultaneously.
Does that make sense? 
Why would one connection attempt result in using one protocol but the next connection attempt result in a different protocol? If the server did change its configuration, any established connections should be closed and all subsequent connections to follow the new server configuration.

**Comment by mathieurousseau** [comment]
That makes sense! 👍 

Thanks!

**Comment by mathieurousseau** [comment]
That makes sense! 👍

Thanks!
