### ISSUE TITLE
Telemetry - custom fields in metadata

### ISSUE THREAD

**Issue by kspe** [sneako/finch#81]
Hey, I wonder if there is a way currently to add custom metadata fields (e.g client_id) to telemetry events emitted by Finch? My use case requires exporting metrics to Prometheus and it would be quite easy to label them with custom tags if those would be available in an event's metadata.

**Comment by ashutoshrishi** [comment]
If you are logging from the same process you generate the `client_id` you can use [Logger.metadata/1](https://hexdocs.pm/logger/Logger.html#module-metadata) for these things. We do that a lot: 

    # Somewhere where you get the client_id
    Logger.metadata(client_id: "something")

And then you could do something like:

    # When sending/logging the metric
    client_id = Logger.medata()[:client_id]

**Comment by kspe** [comment]
Thanks for the hint, not sure though if we are referring same part of the lib, I was thinking about adding custom data into this one, for example, https://github.com/keathley/finch/blob/dd7a07d806945015a34b7b1218703c17891768dc/lib/finch/http1/pool.ex#L26-L31 so I can split my telemetry events by custom ids.

**Comment by keathley** [comment]
Allowing custom metadata is definitely something we want to support. I have a branch with a solution that is most of the way there. I've just been buried under work-related stuff lately.

**Comment by tsloughter** [comment]
@keathley I don't think supporting custom metadata in finch is a good way to go. This feature should be common across all libraries if their metrics/tracing/logging handling is in the same process.

A common way of attaching attributes to a context is what is needed. I've wanted the context part of OpenTelemetry to be split out to its own library and be how this is done, but only if it gets a large backing. The other option is to simply define a key in the process dictionary we all agree on will hold these attributes

**Comment by tsloughter** [comment]
Forgot to note that the usefulness of an actual context library (instead of a key we all agree on to use in the pdict) is support for propagation of these attributes across nodes and hopefully easily across processes one day.

**Comment by keathley** [comment]
@tsloughter I'm definitely in favor of making this consistent. Each library shouldn't have to implement this on its own. I'm not sure if I have an opinion on the specific mechanism. My first impression is that the context is the way to go. We already do this internally at B/R so we can propagate tracing headers, deadlines, and other metadata about any given call.

**Comment by GregMefford** [comment]
I believe that #160 might be related here - @learc83 and I came up with that solution as a reasonably-generic way to plug in the context, but didn't know if you all would be open to doing that as opposed to having some other way to specifically make additional headers available to the request at the time when it needs them.

**Comment by sneako** [comment]
Great point @dvic! I agree, our upcoming `:private` field on the Request struct should be able to be used for this purpose as well.
